Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@den-vasyliev 
den-vasyliev
/
webinar-duckfish
Public
forked from duckfish21/webinar
Fork your own copy of den-vasyliev/webinar-duckfish
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Build and push docker image
fix cicd #3
Jobs
Run details
Workflow file for this run
.github/workflows/cicd.yaml at dd940b8
# job build and push to ghcr.io
name: Build and push docker image
on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}:${{ github.sha }}

fix cicd · den-vasyliev/webinar-duckfish@dd940b8
